# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: aep-type/aep/type/decimal.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'aep-type/aep/type/decimal.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1f\x61\x65p-type/aep/type/decimal.proto\x12\x08\x61\x65p.type\"0\n\x07\x44\x65\x63imal\x12\x13\n\x0bsignificand\x18\x01 \x01(\x03\x12\x10\n\x08\x65xponent\x18\x02 \x01(\x05\x42\'\n\x0c\x64\x65v.aep.typeB\x0c\x44\x65\x63imalProtoP\x01\xf8\x01\x01\xa2\x02\x03\x41\x45Pb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aep_type.aep.type.decimal_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\014dev.aep.typeB\014DecimalProtoP\001\370\001\001\242\002\003AEP'
  _globals['_DECIMAL']._serialized_start=45
  _globals['_DECIMAL']._serialized_end=93
# @@protoc_insertion_point(module_scope)
