# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aep/type/decimal.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x61\x65p/type/decimal.proto\x12\x08\x61\x65p.type\"G\n\x07\x44\x65\x63imal\x12 \n\x0bsignificand\x18\x01 \x01(\x03R\x0bsignificand\x12\x1a\n\x08\x65xponent\x18\x02 \x01(\x05R\x08\x65xponentB`\n\x0c\x63om.aep.typeB\x0c\x44\x65\x63imalProtoP\x01\xf8\x01\x01\xa2\x02\x03\x41TX\xaa\x02\x08\x41\x65p.Type\xca\x02\x08\x41\x65p\\Type\xe2\x02\x14\x41\x65p\\Type\\GPBMetadata\xea\x02\tAep::Typeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aep.type.decimal_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\014com.aep.typeB\014DecimalProtoP\001\370\001\001\242\002\003ATX\252\002\010Aep.Type\312\002\010Aep\\Type\342\002\024Aep\\Type\\GPBMetadata\352\002\tAep::Type'
  _globals['_DECIMAL']._serialized_start=36
  _globals['_DECIMAL']._serialized_end=107
# @@protoc_insertion_point(module_scope)
