# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aep/type/interval.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from buf.validate import validate_pb2 as buf_dot_validate_dot_validate__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x61\x65p/type/interval.proto\x12\x08\x61\x65p.type\x1a\x1b\x62uf/validate/validate.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xcf\x01\n\x08Interval\x12\x39\n\nstart_time\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\tstartTime\x12\x35\n\x08\x65nd_time\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\x07\x65ndTime:Q\xbaHN\x1aL\n\x12Interval.non-empty\x12\x14start must be <= end\x1a this.start_time <= this.end_timeBa\n\x0c\x63om.aep.typeB\rIntervalProtoP\x01\xf8\x01\x01\xa2\x02\x03\x41TX\xaa\x02\x08\x41\x65p.Type\xca\x02\x08\x41\x65p\\Type\xe2\x02\x14\x41\x65p\\Type\\GPBMetadata\xea\x02\tAep::Typeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aep.type.interval_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\014com.aep.typeB\rIntervalProtoP\001\370\001\001\242\002\003ATX\252\002\010Aep.Type\312\002\010Aep\\Type\342\002\024Aep\\Type\\GPBMetadata\352\002\tAep::Type'
  _globals['_INTERVAL']._loaded_options = None
  _globals['_INTERVAL']._serialized_options = b'\272HN\032L\n\022Interval.non-empty\022\024start must be <= end\032 this.start_time <= this.end_time'
  _globals['_INTERVAL']._serialized_start=100
  _globals['_INTERVAL']._serialized_end=307
# @@protoc_insertion_point(module_scope)
