# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aep/type/money.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from aep.type import decimal_pb2 as aep_dot_type_dot_decimal__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x61\x65p/type/money.proto\x12\x08\x61\x65p.type\x1a\x16\x61\x65p/type/decimal.proto\"[\n\x05Money\x12#\n\rcurrency_code\x18\x01 \x01(\tR\x0c\x63urrencyCode\x12-\n\x08quantity\x18\x02 \x01(\x0b\x32\x11.aep.type.DecimalR\x08quantityB^\n\x0c\x63om.aep.typeB\nMoneyProtoP\x01\xf8\x01\x01\xa2\x02\x03\x41TX\xaa\x02\x08\x41\x65p.Type\xca\x02\x08\x41\x65p\\Type\xe2\x02\x14\x41\x65p\\Type\\GPBMetadata\xea\x02\tAep::Typeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aep.type.money_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\014com.aep.typeB\nMoneyProtoP\001\370\001\001\242\002\003ATX\252\002\010Aep.Type\312\002\010Aep\\Type\342\002\024Aep\\Type\\GPBMetadata\352\002\tAep::Type'
  _globals['_MONEY']._serialized_start=58
  _globals['_MONEY']._serialized_end=149
# @@protoc_insertion_point(module_scope)
