# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aep/type/phone_number.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from buf.validate import validate_pb2 as buf_dot_validate_dot_validate__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x61\x65p/type/phone_number.proto\x12\x08\x61\x65p.type\x1a\x1b\x62uf/validate/validate.proto\"\xaa\x02\n\x0bPhoneNumber\x12\x35\n\x06number\x18\x01 \x01(\tB\x1b\xbaH\x18r\x16\x32\x14^\\+[0-9]{1,3}[0-9]+$H\x00R\x06number\x12@\n\nshort_code\x18\x02 \x01(\x0b\x32\x1f.aep.type.PhoneNumber.ShortCodeH\x00R\tshortCode\x12%\n\textension\x18\x03 \x01(\tB\x07\xbaH\x04r\x02\x18(R\textension\x1as\n\tShortCode\x12=\n\x0bregion_code\x18\x01 \x01(\tB\x1c\xbaH\x19r\x17\x32\x15^([A-Z]{2}|[0-9]{3})$R\nregionCode\x12\'\n\x06number\x18\x02 \x01(\tB\x0f\xbaH\x0cr\n2\x08^[0-9]+$R\x06numberB\x06\n\x04kindBd\n\x0c\x63om.aep.typeB\x10PhoneNumberProtoP\x01\xf8\x01\x01\xa2\x02\x03\x41TX\xaa\x02\x08\x41\x65p.Type\xca\x02\x08\x41\x65p\\Type\xe2\x02\x14\x41\x65p\\Type\\GPBMetadata\xea\x02\tAep::Typeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aep.type.phone_number_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\014com.aep.typeB\020PhoneNumberProtoP\001\370\001\001\242\002\003ATX\252\002\010Aep.Type\312\002\010Aep\\Type\342\002\024Aep\\Type\\GPBMetadata\352\002\tAep::Type'
  _globals['_PHONENUMBER_SHORTCODE'].fields_by_name['region_code']._loaded_options = None
  _globals['_PHONENUMBER_SHORTCODE'].fields_by_name['region_code']._serialized_options = b'\272H\031r\0272\025^([A-Z]{2}|[0-9]{3})$'
  _globals['_PHONENUMBER_SHORTCODE'].fields_by_name['number']._loaded_options = None
  _globals['_PHONENUMBER_SHORTCODE'].fields_by_name['number']._serialized_options = b'\272H\014r\n2\010^[0-9]+$'
  _globals['_PHONENUMBER'].fields_by_name['number']._loaded_options = None
  _globals['_PHONENUMBER'].fields_by_name['number']._serialized_options = b'\272H\030r\0262\024^\\+[0-9]{1,3}[0-9]+$'
  _globals['_PHONENUMBER'].fields_by_name['extension']._loaded_options = None
  _globals['_PHONENUMBER'].fields_by_name['extension']._serialized_options = b'\272H\004r\002\030('
  _globals['_PHONENUMBER']._serialized_start=71
  _globals['_PHONENUMBER']._serialized_end=369
  _globals['_PHONENUMBER_SHORTCODE']._serialized_start=246
  _globals['_PHONENUMBER_SHORTCODE']._serialized_end=361
# @@protoc_insertion_point(module_scope)
