---
name: build-test-and-publish-protos
on:
  push:
    paths:
      - .github/workflows/build-and-publish-protos.yaml
      - "proto/**"
      - buf.yaml
      - buf.lock
  pull_request:
    paths:
      - .github/workflows/build-and-publish-protos.yaml
      - "proto/**"
      - buf.yaml
      - buf.lock
    types: [opened, synchronize, reopened, labeled, unlabeled]
  delete:
permissions:
  contents: read
  pull-requests: write
jobs:
  buf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bufbuild/buf-action@v0.2
        with:
          token: ${{ secrets.BUF_TOKEN }}
          pr_comment: false
          format: false
